### ISSUE TITLE
Clothing slider crashes ClimApp

### ISSUE THREAD

**Issue by FritzdorfSport** [frksteenhoff/ClimApp#142] opened 2020-03-26 09:19 UTC
I move the slider, but the categorisation doesn't change, and ClimApp crashes

**To Reproduce**
Open ClimApp
Tap "Clothing"
Move slider

**Expected behavior**
Categorisation changes
Can continue using ClimApp

 iOS 13.3.1 on iPhone 7

![IMG_74C51053729A-1](https://user-images.githubusercontent.com/10878963/77630392-3c1d3980-6f4b-11ea-9551-9e591a234ceb.jpeg)

**Comment by FritzdorfSport** [comment] 2020-03-26 09:26
Further investigation reveals the crash may occur only when:

1. Moving the slider all the way to the left (attempting to choose Summer attire), and/or
2. When moving the slider all the way from Winter attire to Summer attire (as shown  in the screen grab)

**Comment by FritzdorfSport** [comment] 2020-03-26 09:27
Reproduced the crash by moving from Casual to Summer, as seen here:

![IMG_3ACC6128B8B9-1](https://user-images.githubusercontent.com/10878963/77631058-5ad00000-6f4c-11ea-893f-5c5b2e0790fc.jpeg)

**Comment by BorisKingma** [comment] 2020-03-26 09:33
Thank you @FritzdorfSport ,

The report is clear - however, I cannot reproduce it on my end. Perhaps it is related to specific weather conditions. Would you be able to test this for a custom location - you can use the custom location feature for that? ( alternatively you can also send me your location via mail (- not the public github).

Kind regards,
Boris

**Comment by FritzdorfSport** [comment] 2020-03-26 09:42
I have tried it for North Africa 33.44, 10.69

and

Sweden 55.54, 12.92


and get the same error 🙁


________________________________

**Comment by BorisKingma** [comment] 2020-03-26 09:50
what is the activity level in your examples?

**Comment by FritzdorfSport** [comment] 2020-03-26 09:52
I have just tried all activity levels, and still get the error and crash.
________________________________

**Comment by BorisKingma** [comment] 2020-03-26 09:53
what is the version of the app? you can check that in settings/about

**Comment by FritzdorfSport** [comment] 2020-03-26 09:54
App version 3.2.0

Knowledgebase 2.058
________________________________

**Comment by BorisKingma** [comment] 2020-03-26 09:58
very interesting, I will check with other iOS users, because on android and the ios emulator this issue is not reproducible.

Kind regards,
Boris

**Comment by BorisKingma** [comment] 2020-09-11 07:53
sorry, not able to reproduce it in newer versions of the app, perhaps there was an issue that is already fixed in newer versions.

**Closed as completed by BorisKingma** 2020-09-11 07:53 UTC
